IS_TRAIN: True
HEADLESS: True
GPU_ID: '0,1,2,3'

HOLDOUT:
    MODE: False

TRAIN: 
    CKPT_DIR: "training-level3-2-occ"
    CKPT_ITER: 100000
    SEED: 123
    WEIGHT_LOSS_REINFORCE: 0.0001
    VISUAL_FREQ: 1000
    EPISODES: 100000
    CURRICULUM_MODE: "one_or_two_objs"
    EXP_DATADIR: "training-l4-overall"

