IS_TRAIN: True
HEADLESS: True
GPU_ID: '0'

HOLDOUT:
    MODE: False

TRAIN: 
    CKPT_DIR: "training-level1-1-vis"
    CKPT_ITER: 900000
    SEED: 123
    VISUAL_FREQ: 1000
    EPISODES: 900000
    CURRICULUM_MODE: "two_objs_without_occlusion"
    EXP_DATADIR: "training-level2-2-vis"

